#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Webserver

# General
WEB_DOCUMENT_ROOT=/app/
WEB_DOCUMENT_INDEX=index.php
CLI_SCRIPT=php /app/index.php

#######################################
# SSH settings
# SSH public key (without comment):
# -> ssh-rsa AAAAB3Nza....
#  Github public ssh keys:
# -> https://github.com/USERNAME.keys
SSH_AUTH_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsWJYZ9N+jslAMdHHQ16fxafpqdfRkGRamKsogprD8mqK0jJAthwHpm7IPWIpqF5BBfha6+/EuZmVHztoqVltxuVHP0BKbLXgqKFudZjWrkWS9gTh5yzendpG2ija6wuSX8vGcMopWZRp0JPlILmNc3ENR6usf8RvoxSR59sSeSBueVkex5G9VyWT+0L/ENswsqA8E27dSlVvQv1wHz4ZSWUe/CLYS5QJ2WPF/BLLgfOYjMhRqdJyI6/gNOVWcloRNSygsgZA0COZOM0wgTupdl1gXchV4Zl6vlxHYjq80wWiDLeFNFW1QspndGK+kpK6mjQk8kob6Nvfpsbpr2h2t openbase-key"

#######################################
# MySQL settings
# -> if you change these settings
#    you have to remove the database:
#         docker-compose rm mysql
#    because it's stored database in
#    volume and provisioning is only
#    done once.
MYSQL_ROOT_PASSWORD=UKffzUMarxUBrXPX7gaPoZNfaaXXs6x
MYSQL_USER=devwp
MYSQL_PASSWORD=UKffzUMarxUBrXPX7gaPoZNfaaXXs6y
MYSQL_DATABASE=wordpress

#######################################
# PostgreSQL settings
POSTGRES_USER=dev
POSTGRES_PASSWORD=dev

#######################################
# FTP settings
FTP_USER=dev
FTP_PASSWORD=dev
FTP_PATH=/storage/ftp/
#FTP_PATH=/app/
